### ISSUE TITLE
0.0.4 Possibly undesired behavior

### ISSUE THREAD

**Issue by iotech-fvtt** [wsaunders1014/TerrainLayer#6]
FVTT 0.6.6
D&D5e 0.98
via Node, self hosted

See that players can now see difficult terrain markers, great! Changes to terrain are broadcast to players. If a player is disconnected, and while offline, the GM makes changes, when the player logs back in, the changes are not received.

Reproduction:
DM & Player log in
DM: Mark some terrain as difficult
Player: See the terrain markers
Player: log off/get disconnected (or maybe GM is prepping and player is not connected at all!)
DM makes changes to terrain
Player: Logs on, changes to terrain layer are not shown to player, only what they saw when last connected.

**Comment by wsaunders1014** [comment]
Okay I can't replicate in 0.0.5 so maybe I addressed it. I just pushed 0.0.6, so reopen if it's still an issue.
